name: default

on: [push, pull_request]

jobs:
  stylua:
    name: stylua formatter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          args: --color always --check .

  selene:
    name: selene linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          # Github secret token
          token: ${{ secrets.GITHUB_TOKEN }}
          # selene arguments
          args: --display-style=quiet .
          # selene version
          version: 0.12.1
