name: "release"
on:
  push:
    tags:
      - "*"
jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: |
            A collection of common configurations for Neovim's colorschemes
            plugins.
          detailed_description: |
            This plugin allows for installing colorschemes.
          licence: "MIT"
