name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim-versions: ["stable", "nightly"]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: run test with vusted
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          vusted ./tests
